# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Act1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Act1.proto',
  package='tests',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nAct1.proto\x12\x05tests\"\x1f\n\x0b\x41\x63t1Request\x12\x10\n\x08Username\x18\x01 \x01(\t\"%\n\x08\x62\x61sicMsg\x12\x0c\n\x04\x46rom\x18\x01 \x01(\t\x12\x0b\n\x03Msg\x18\x02 \x01(\t\">\n\x07\x46ullMsg\x12\x0c\n\x04\x46rom\x18\x01 \x01(\t\x12\n\n\x02To\x18\x02 \x01(\t\x12\x0b\n\x03Msg\x18\x03 \x01(\t\x12\x0c\n\x04\x44\x61te\x18\x04 \x01(\t2\x9a\x01\n\x04\x43hat\x12\x32\n\tHandShake\x12\x12.tests.Act1Request\x1a\x0f.tests.basicMsg\"\x00\x12-\n\x08\x44ispatch\x12\x0e.tests.FullMsg\x1a\x0f.tests.basicMsg\"\x00\x12/\n\x08Retrieve\x12\x0f.tests.basicMsg\x1a\x0e.tests.FullMsg\"\x00\x30\x01\x32@\n\x07\x43lients\x12\x35\n\nGetClients\x12\x0f.tests.basicMsg\x1a\x12.tests.Act1Request\"\x00\x30\x01\x32;\n\x06GetAll\x12\x31\n\nGetAllSent\x12\x0f.tests.basicMsg\x1a\x0e.tests.FullMsg\"\x00\x30\x01\x62\x06proto3')
)




_ACT1REQUEST = _descriptor.Descriptor(
  name='Act1Request',
  full_name='tests.Act1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Username', full_name='tests.Act1Request.Username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=52,
)


_BASICMSG = _descriptor.Descriptor(
  name='basicMsg',
  full_name='tests.basicMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='From', full_name='tests.basicMsg.From', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Msg', full_name='tests.basicMsg.Msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=91,
)


_FULLMSG = _descriptor.Descriptor(
  name='FullMsg',
  full_name='tests.FullMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='From', full_name='tests.FullMsg.From', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='To', full_name='tests.FullMsg.To', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Msg', full_name='tests.FullMsg.Msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Date', full_name='tests.FullMsg.Date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['Act1Request'] = _ACT1REQUEST
DESCRIPTOR.message_types_by_name['basicMsg'] = _BASICMSG
DESCRIPTOR.message_types_by_name['FullMsg'] = _FULLMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Act1Request = _reflection.GeneratedProtocolMessageType('Act1Request', (_message.Message,), {
  'DESCRIPTOR' : _ACT1REQUEST,
  '__module__' : 'Act1_pb2'
  # @@protoc_insertion_point(class_scope:tests.Act1Request)
  })
_sym_db.RegisterMessage(Act1Request)

basicMsg = _reflection.GeneratedProtocolMessageType('basicMsg', (_message.Message,), {
  'DESCRIPTOR' : _BASICMSG,
  '__module__' : 'Act1_pb2'
  # @@protoc_insertion_point(class_scope:tests.basicMsg)
  })
_sym_db.RegisterMessage(basicMsg)

FullMsg = _reflection.GeneratedProtocolMessageType('FullMsg', (_message.Message,), {
  'DESCRIPTOR' : _FULLMSG,
  '__module__' : 'Act1_pb2'
  # @@protoc_insertion_point(class_scope:tests.FullMsg)
  })
_sym_db.RegisterMessage(FullMsg)



_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='tests.Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=158,
  serialized_end=312,
  methods=[
  _descriptor.MethodDescriptor(
    name='HandShake',
    full_name='tests.Chat.HandShake',
    index=0,
    containing_service=None,
    input_type=_ACT1REQUEST,
    output_type=_BASICMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Dispatch',
    full_name='tests.Chat.Dispatch',
    index=1,
    containing_service=None,
    input_type=_FULLMSG,
    output_type=_BASICMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='tests.Chat.Retrieve',
    index=2,
    containing_service=None,
    input_type=_BASICMSG,
    output_type=_FULLMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT


_CLIENTS = _descriptor.ServiceDescriptor(
  name='Clients',
  full_name='tests.Clients',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=314,
  serialized_end=378,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetClients',
    full_name='tests.Clients.GetClients',
    index=0,
    containing_service=None,
    input_type=_BASICMSG,
    output_type=_ACT1REQUEST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENTS)

DESCRIPTOR.services_by_name['Clients'] = _CLIENTS


_GETALL = _descriptor.ServiceDescriptor(
  name='GetAll',
  full_name='tests.GetAll',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=380,
  serialized_end=439,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllSent',
    full_name='tests.GetAll.GetAllSent',
    index=0,
    containing_service=None,
    input_type=_BASICMSG,
    output_type=_FULLMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETALL)

DESCRIPTOR.services_by_name['GetAll'] = _GETALL

# @@protoc_insertion_point(module_scope)
